<?php


/**
 * Implementation of hook_menu().
 */
function wxwork_menu() {
    $items['admin/config/wxwork'] = array(
        'title' => '企业微信',
        'description' => 'Administer your wxwork.',
        'page callback' => 'system_admin_menu_block_page',
        'access arguments' => array('access administration pages'),
        'file path' => drupal_get_path('module', 'system'),
        'file' => 'system.admin.inc',
        'weight' => 0,
        'position' => 'right',
    );
    $items['admin/config/wxwork/config'] = array(
        'title' => '配置应用',
        'description' => '配置企业微信中的应用.',
        'page callback' => 'wxwork_get_apps',
        'access arguments' => array('access administration pages'),
        'type' => MENU_CALLBACK,
        'file' => 'wxwork.page.inc'
    );
    $items['admin/config/wxwork/app/add'] = array(
        'title' => '增加应用',
        'description' => '增加企业微信中的应用.',
        'page callback' => 'drupal_get_form',
        'access arguments' => array('access administration pages'),
        'page arguments' => array('wxwork_app_form'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'wxwork.admin.inc'
    );
    return $items;
}

function test_callback() {
    return "test page";
}

function _wxwork_init() {
    $wxwork = &drupal_static(__FUNCTION__);
    if (!isset($wxwork)) {
        module_load_include('php', 'wxwork', 'sdk/wxwork.class');
        $url = '';
        $options = array();
        $wxwork = new WeWork($options);
    }
    return $wxwork;
}
